version: "3"

services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: library-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    tty: true